// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ2VqCdYVTl304aSDZBhnEFUfl_eeLHko',
    appId: '1:1000311694960:web:bb83e5ff85366415fd76b5',
    messagingSenderId: '1000311694960',
    projectId: 'frameworkdesafio',
    authDomain: 'frameworkdesafio.firebaseapp.com',
    storageBucket: 'frameworkdesafio.appspot.com',
    measurementId: 'G-EH5VVDXSCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHL3vfB_kk4H19Dw5ndbROdWF759-qITA',
    appId: '1:1000311694960:android:8e4255a0242e703dfd76b5',
    messagingSenderId: '1000311694960',
    projectId: 'frameworkdesafio',
    storageBucket: 'frameworkdesafio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhgMNfgKtFtO0ouN8naCJjLC4Ll-01dTk',
    appId: '1:1000311694960:ios:a8638ac622405e3bfd76b5',
    messagingSenderId: '1000311694960',
    projectId: 'frameworkdesafio',
    storageBucket: 'frameworkdesafio.appspot.com',
    androidClientId: '1000311694960-rfb10kfe0m5u78jjdn4d1ug0f55aoioh.apps.googleusercontent.com',
    iosClientId: '1000311694960-t3g9jg6khb0p85tb2uvja3hva1rghbo0.apps.googleusercontent.com',
    iosBundleId: 'com.framework.ecommerce',
  );
}
